[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = qio
board_build.f_cpu = 240000000L

lib_deps = 
    miguelbalboa/MFRC522@^1.4.10
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^6.21.3